openapi: '3.1.4'

info:
  title: Vana Logistiek App
  description: Een ticket-systeem voor de supporting teams op Castlefest
  version: 1.0.0
  license:
    name: GNU General Public License 3.0
    identifier: GPL-3.0


servers:
  - description: Quarkus Dev Mode
    url: http://localhost:8000/

security:
  - jwt: []

paths:
  /version:
    summary: Returns app version

  /threads:
    summary: Routes for threads about stuff
    post:
      operationId: createThread
      description: Create a new thread for a vendor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createThread"

components:
  schemas:
    createThread:
      type: object
      required:
        - name
        - vendor_id
      properties:
        name:
          type: string
        vendor_id:
          type: number
          minimum: 1
